console.log('Hello from semversionify!');
console.log('Create new feature');
console.log('I am a change that doesn\'t trigger release');
console.log('I am a breaking change.');
console.log('I am a breaking change. Take 2');
console.log('I am a fix');
console.log('I am a fix 2');
console.log('I am a chore');
console.log('I am feature 1');
console.log('I am fix 3');